PImage WhyTho;
PImage moo;
PImage APC;
PImage Saints;
PImage CastrolMotorOil;
PImage Constantine;
PImage NextStepInHumanEvolution;
PImage NuclearHairSwap;
PImage Eurus;
PImage FaceSwap;
PImage airship;
PImage afro;
PImage WhyTho13;
PImage kurbanbayrami;
PImage soap;
PImage WhyTho16;
PImage WhyTho17;
PImage WhyTho18;
PImage syfy;
PImage Numbers;

void setup () {
  size (1080,560);
  WhyTho=loadImage ("images/WHY.jpg");
  moo=loadImage ("images/all backwards.jpg");
  APC=loadImage ("images/apc2.jpg");
  Saints=loadImage ("images/boondock2.jpg");
 CastrolMotorOil=loadImage ("images/castro.jpg");
 Constantine=loadImage ("images/cons.jpg");
NextStepInHumanEvolution=loadImage ("images/cuddly.jpg");
NuclearHairSwap=loadImage ("images/donald jong un.jpg");
Eurus=loadImage ("images/eurus.jpg");
FaceSwap=loadImage ("images/fwapsace.jpg");
airship=loadImage ("images/Let's Build A Powerful Soviet Airship.jpg");
afro=loadImage ("images/loading afro.jpg");
WhyTho13=loadImage ("images/new earth.jpg");
kurbanbayrami=loadImage ("images/natural.jpg");
soap=loadImage ("images/fc.jpg");
WhyTho16=loadImage ("images/structure.jpg");
WhyTho17=loadImage ("images/the entrance.jpg");
WhyTho18=loadImage ("images/underway_by_suzythebutcher.jpg");
syfy=loadImage ("images/Sea City Urbanizing the Oceans, STARLOG #18 magazine cover, 1980 by David Mattingly.jpg");
Numbers=loadImage ("images/math.jpg");
}

void draw () {
  background (0);
  image(WhyTho,150,0);
  WhyTho.resize (150,200);
  image(moo,0,0);
  moo.resize (150,200);
  image(APC,300,0);
  APC.resize (200,200);
  image(Saints,500,0);
  Saints.resize (300,200);
 image(CastrolMotorOil,800,0);
  //Hocam, çerçeve dışına çıktığının farkındayım ama görüntü bozulsun istemedim.
  CastrolMotorOil.resize (300,200);
   image(Constantine,0,200);
  Constantine.resize (120,200);
  image(NextStepInHumanEvolution,120,200);
  NextStepInHumanEvolution.resize (280,200);
   image(NuclearHairSwap,400,200);
  NuclearHairSwap.resize (300,200);
  image(Eurus,700,200);
  Eurus.resize (250,200);
  image(FaceSwap,950,200);
  FaceSwap.resize (130,200);
  image(airship,0,400);
  airship.resize (160,160);
   image(afro,160,400);
  afro.resize (160,160);
   image(WhyTho13,320,400);
  WhyTho13.resize (100,160);
   image(kurbanbayrami,420,400);
  kurbanbayrami.resize (125,160);
    image(soap,545,400);
  soap.resize (105,160);
  image(WhyTho16,650,400);
  WhyTho16.resize (100,160);
  image(WhyTho17,750,400);
  WhyTho17.resize (80,160);
 image(WhyTho18,830,400);
  WhyTho18.resize (100,160);
   image(syfy,930,400);
  syfy.resize (75,160);
   image(Numbers,1005,400);
  Numbers.resize (75,160);
}